name: eshop_multivendor
description: eShop Multivendor App
publish_to: "none"

version: 3.0.0+47

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.0.5
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.4
  firebase_messaging: ^15.1.3
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.15.0
  firebase_auth: ^5.2.0
  sms_autofill: ^2.4.1
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.0
  file_picker: ^10.1.5
  shimmer: ^3.0.0
  geocoding: ^4.0.0
  paystack_for_flutter: ^1.0.4
  flutter_html_to_pdf:
    git:
      url: https://github.com/mohammadhprp/flutter_html_to_pdf2
      ref: master
  permission_handler: ^12.0.0+1
  in_app_review: ^2.0.9
  open_filex: ^4.7.0
  provider: ^6.1.5
  share_plus: ^11.0.0
  firebase_core: ^3.6.0
  video_player: ^2.9.5
  flutter_svg: ^2.0.9
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  sqflite: ^2.3.2
  version: ^3.0.2
  flutter_downloader: ^1.9.1
  speech_to_text: ^7.3.0
  tuple: ^2.0.2
  lottie: ^3.0.0
  flutter_stripe: ^11.0.0
  flutter_widget_from_html: ^0.15.0
  flutter_bloc: ^9.1.1
  dio: ^5.6.0
  device_info_plus: ^11.4.0
  cached_network_image: ^3.4.1
  phonepe_payment_sdk: ^3.0.0
  app_links: ^6.1.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  external_path: ^2.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  country_pickers: ^3.0.0
  flutter_styled_toast: ^2.2.1
  paytmpayments_allinonesdk: ^1.0.4
  myfatoorah_flutter: ^3.2.5
  razorpay_flutter: ^1.3.5
  intl_phone_field: ^3.2.0
  youtube_player_flutter: ^9.1.0
  readmore: ^3.0.0
  change_app_package_name: ^1.5.0
  http: ^1.4.0
  grouped_buttons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/svg/logos/
    - assets/animation/
    - assets/languages/
    - assets/images/flags/
    - assets/eShop.db
    - assets/countryCodes/
  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf